[wazuhagents]
#77.81.6.120
10.10.0.21 ansible_ssh_common_args='-o ProxyJump=debian@77.81.6.120'
10.10.0.22 ansible_ssh_common_args='-o ProxyJump=debian@77.81.6.120'
10.10.0.23 ansible_ssh_common_args='-o ProxyJump=debian@77.81.6.120'

[wazuhagents:vars]
ansible_user=debian