- name: Setting up trivy on Wazuh Agents
  hosts: wazuhagents
  become: yes

  tasks:

    - name: Ensure required packages are installed
      apt:
        name: 
          - wget
          - gnupg
        state: present
        update_cache: yes

    - name: Add Trivy GPG key
      ansible.builtin.apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present
        keyring: /usr/share/keyrings/trivy.gpg

    - name: Add Trivy APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main"
        filename: trivy
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Trivy
      apt:
        name: trivy
        state: present